-- changeset agafonnikov:1
create table _user (
                       id int generated by default as identity primary key,
                       login varchar(255),
                       password varchar(255),
                       role varchar(255)
);
--rollback drop table _user