
select * from _user;

create table _user (
                       id INTEGER PRIMARY KEY,
                       login varchar(64),
                       password varchar(64),
                       role varchar(64)
);

insert into _user (login, password, role)
values
    ('bm', '$2a$10$yfOj9fqUxKAJdoA4rAcfS.WiBAR1BQze2kbA.15Zkw7wncYL.TVnG', 'USER'),
    ('dm', '$2a$10$yfOj9fqUxKAJdoA4rAcfS.WiBAR1BQze2kbA.15Zkw7wncYL.TVnG', 'USER'),
    ('i@m.ru', '$2a$10$yfOj9fqUxKAJdoA4rAcfS.WiBAR1BQze2kbA.15Zkw7wncYL.TVnG', 'USER')
;

drop table _user;


select * from _files;

drop table _files;

create table _files (
                        name varchar(64),
                        type  varchar(64),
                        data bytea,
                        user_id INTEGER,
                        PRIMARY KEY (name, user_id),
                        constraint fk_user
                            foreign key (user_id)
                                references _user (id)
);

insert into _files (name, type, data, user_id)
values
    ('Docdoc', 'txt', "17453", 2),
    ('IMAGEpng', 'png', "20000", 1),
    ('refdoc', 'txt', "3000", 3)
;

select name, type, data from "_files" f
                                 join "_user" u on f.user_id = u.id
where u.id = 1;

SELECT  * from _black_list_jwt_tokens;

create table _black_list_jwt_tokens (
    token text PRIMARY KEY
);

drop table _black_list_jwt_tokens;



-----------------------------------------------------------------------

insert into persons (name, surname, age, phone_number, city_of_living)
values
    ('Bob', 'Lame', 34, '+19877898888', 'BOSTON'),
    ('Denis', 'Kronov', 22, '+71345798854', 'MOSCOW'),
    ('Ivan', 'Dronov', 44, '+75654677742', 'MOSCOW'),
    ('Mike', 'Vane', 32, '+59999678666', 'LONDON'),
    ('Ron', 'Jole', 48, '+71345798854', 'MOSCOW'),
    ('Katar', 'Matar', 29, '+28767688868', 'ROME'),
    ('Grigoriy', 'Kinov', 19, '+71345798854', 'MOSCOW')
;

select * from persons;

create table _user (
                       id long,
                       firstname varchar(64),
                       lastname varchar(64),
                       email varchar(64),
                       password varchar(64),
                       primary KEY (id)
);

select * from _user;

________________________________________________________________________

create table CUSTOMERS (
                           id integer generated by default as identity primary key,
                           name text,
                           surname text,
                           age integer,
                           phone_number text
);


insert into CUSTOMERS (name, surname, age, phone_number)
values
    ('Bob', 'Lame', 34, '+19877898888'),
    ('ALexeY', 'Kronov', 22, '+71345798854'),
    ('Ivan', 'Dronov', 44, '+75654677742'),
    ('ALEXEY', 'Vane', 32, '+59999678666'),
    ('Ron', 'Jole', 48, '+71345798854'),
    ('Katar', 'Matar', 29, '+28767688868'),
    ('Denis', 'Kinov', 19, '+71345798854');



create table ORDERS (
                        id integer generated by default as identity primary key,
                        date date,
                        customer_id integer,
                        product_name text,
                        amount integer,
                        constraint fk_customer
                            foreign key (customer_id)
                                references CUSTOMERS (id)
);



insert into ORDERS (date, customer_id, product_name, amount)
values
    ('2021-03-23', 1, 'TV', 10000),
    ('2022-11-13', 2, 'PS5', 59999),
    ('2022-12-10', 3, 'Wi-Fi', 3000),
    ('2023-01-02', 4, 'Keyboard', 3299),
    ('2023-02-13', 5, 'Mouse', 2200),
    ('2023-03-01', 6, 'AUX', 300),
    ('2023-04-21', 7, 'XBOX', 49000),
    ('2023-05-15', 2, 'iPhone', 70000),
    ('2023-06-17', 4, 'USB-USB cable', 500),
    ('2023-07-29', 5, 'TV', 37800);

create table PERSONS (
                         name text,
                         surname text,
                         age integer,
                         phone_number text,
                         city_of_living text
);

insert into persons (name, surname, age, phone_number, city_of_living)
values
    ('Bob', 'Lame', 34, '+19877898888', 'BOSTON'),
    ('Denis', 'Kronov', 22, '+71345798854', 'MOSCOW'),
    ('Ivan', 'Dronov', 44, '+75654677742', 'MOSCOW'),
    ('Mike', 'Vane', 32, '+59999678666', 'LONDON'),
    ('Ron', 'Jole', 48, '+71345798854', 'MOSCOW'),
    ('Katar', 'Matar', 29, '+28767688868', 'ROME'),
    ('Grigoriy', 'Kinov', 19, '+71345798854', 'MOSCOW')
;

select * from PERSONS;
select * from ORDERS;
select * from CUSTOMERS;

drop table persons;

select product_name from ORDERS o
                             join CUSTOMERS c on o.customer_id = c.id
where lower(c.name) = 'alexey';